### PR TITLE
Remove export field, source code is located in the root of library

### PR DESCRIPTION
**Pull request by ivankravets**
@RobTillaart, do you plan to split other libraries (https://github.com/RobTillaart/Arduino.git) into own repository?

### CODE REVIEW

**Comment by ivankravets** [comment]
Could you also remove `export` from other libraries? https://github.com/RobTillaart/DHTNew/blob/master/library.json#L19

Thanks!

**Comment by RobTillaart** [comment]
Yes, the plan is to give all the libraries their own repo. This improves version control and issue tracking.  
At least until then the big repo is kept alive.

**Comment by RobTillaart** [comment]
I will make a note of that export path in library.json for the other repo's. 
Assume that means a new release to be effective?

**Comment by ivankravets** [comment]
Yes, just remove `export` field. Later, when all libraries are split, please ping me here and we will update existing registered packages with new manifest URLs.

**Pull request merged**
